### PR TITLE
Alpine Image && Add '/composer/vendor/bin' in PATH

### LINKED ISSUE #1: Changing entrypoint
Actually we can't use this docker image with gitlab-ci.
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1421

The right way to fix this is to change the entrypoint, see the docker best practices :
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/entrypoint

Thanks

### PR DESCRIPTION
**Pull request by flolivaud**
close #1 #3

### CODE REVIEW

**Comment by flolivaud** [comment]
close #1 #3

**Comment by ypereirareis** [comment]
OK... Thx!

But could you please add your changes into a 3.0 directory to allow me to create a new docker image tag and not break the previous one (2.0).

:smile:

**Comment by flolivaud** [comment]
Done.

**Comment by flolivaud** [comment]
I forgot to add tests in `.travis.yml`. It's done now.

**Comment by ypereirareis** [comment]
Thx !
Gonna build the docker image with tag 3.0 in a few minutes !

**Comment by ypereirareis** [comment]
Image (3.0) building : https://hub.docker.com/r/ypereirareis/php7cc/builds/

**Pull request merged**
